// Generated by CoffeeScript 1.7.1
var sched;

sched = null;

$.get('http://api.bart.gov/api/sched.aspx', {
  cmd: 'routesched',
  route: 8,
  key: 'UDLR-ZTYV-ENAU-LPAW'
}, function(data) {
  return sched = data;
});

//# sourceMappingURL=fetcher.map
